### PR TITLE
Community/apiv10

### PR DESCRIPTION
**Pull request by ooliver1**
## Checklist

- [ ] If code changes were made then they have been tested.
  - [ ] I have updated the documentation to reflect the changes.
  - [ ] I have run `task pyright` and fixed the relevant issues.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by EmmmaTech** [comment]
Alright yeah this PR is super good and very ready for merge

**Review by spifory — APPROVED** [review]
yes.

**Review by ooliver1 — COMMENTED** [review]
bad

**Review by TAG-Epic — APPROVED** [review]
h

**Pull request closed without merging**
